name: lambda_server
description: A sample command-line application.
version: 1.0.1
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  aws_dynamodb_api: ^2.0.0
  aws_lambda_dart_runtime_ns: ^0.0.13
  datasource:
    git: https://github.com/minia68/mv-tr__datasource.git
  dio: ^5.6.0
  domain:
    git: https://github.com/minia68/mv-tr__domain.git
  movie_info_provider:
    git: https://github.com/minia68/mv-tr__movie_info_provider.git

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^6.0.0
